#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="${ROOT_DIR}/backend"
FRONTEND_DIR="${ROOT_DIR}/frontend"

PUBLIC_IP="${PUBLIC_IP:-104.214.177.7}"
BACKEND_PORT="${BACKEND_PORT:-3001}"
BACKEND_BIND_HOST="${BACKEND_BIND_HOST:-0.0.0.0}"
BACKEND_INTERNAL_URL="http://${BACKEND_BIND_HOST}:${BACKEND_PORT}"

FRONTEND_PROXY_PORT="${FRONTEND_PROXY_PORT:-3000}"
FRONTEND_DEV_PORT="${FRONTEND_DEV_PORT:-3100}"
FRONTEND_DEV_HOST="${FRONTEND_DEV_HOST:-127.0.0.1}"
FRONTEND_PROXY_HOST="${FRONTEND_PROXY_HOST:-0.0.0.0}"
FRONTEND_PUBLIC_HOST="${FRONTEND_PUBLIC_HOST:-${PUBLIC_IP}}"

FRONTEND_PUBLIC_URL="http://${FRONTEND_PUBLIC_HOST}:${FRONTEND_PROXY_PORT}"
FRONTEND_INTERNAL_URL="http://${FRONTEND_DEV_HOST}:${FRONTEND_DEV_PORT}"

CLIENT_API_URL="${FRONTEND_PUBLIC_URL}"
CLIENT_WS_URL="ws://${FRONTEND_PUBLIC_HOST}:${FRONTEND_PROXY_PORT}/ws"

FRONTEND_ALLOWED_ORIGINS="${FRONTEND_PUBLIC_URL}"

export PUBLIC_IP BACKEND_PORT BACKEND_BIND_HOST BACKEND_INTERNAL_URL FRONTEND_PROXY_PORT FRONTEND_DEV_PORT FRONTEND_DEV_HOST FRONTEND_PROXY_HOST FRONTEND_PUBLIC_HOST FRONTEND_PUBLIC_URL FRONTEND_INTERNAL_URL CLIENT_API_URL CLIENT_WS_URL FRONTEND_ALLOWED_ORIGINS

echo "Starting backend on ${BACKEND_BIND_HOST}:${BACKEND_PORT} (public via proxy ${CLIENT_API_URL})…"
(
  cd "${BACKEND_DIR}"
  HOST="${BACKEND_BIND_HOST}" \
  PORT="${BACKEND_PORT}" \
  FRONTEND_URL="${FRONTEND_ALLOWED_ORIGINS}" \
  npm run start
) &
BACKEND_PID=$!

echo "Starting frontend dev server on ${FRONTEND_DEV_HOST}:${FRONTEND_DEV_PORT} (public via proxy ${FRONTEND_PUBLIC_URL})…"
(
  cd "${FRONTEND_DIR}"
  TURBOPACK=0 \
  NEXT_PUBLIC_API_URL="${CLIENT_API_URL}" \
  NEXT_PUBLIC_WS_URL="${CLIENT_WS_URL}" \
  npm run dev -- --hostname "${FRONTEND_DEV_HOST}" --port "${FRONTEND_DEV_PORT}"
) &
FRONTEND_PID=$!

echo "Starting local proxy on ${FRONTEND_PROXY_HOST}:${FRONTEND_PROXY_PORT}…"
(
  cd "${ROOT_DIR}"
  PROXY_HOST="${FRONTEND_PROXY_HOST}" \
  PROXY_PORT="${FRONTEND_PROXY_PORT}" \
  BACKEND_TARGET="${BACKEND_INTERNAL_URL}" \
  FRONTEND_TARGET="http://${FRONTEND_DEV_HOST}:${FRONTEND_DEV_PORT}" \
  node ./scripts/dev-proxy.mjs
) &
PROXY_PID=$!

cleanup() {
  echo "Stopping servers…"
  kill "${PROXY_PID}" "${BACKEND_PID}" "${FRONTEND_PID}" >/dev/null 2>&1 || true
}

trap cleanup EXIT INT TERM

wait

